### PR TITLE
Change description and updated director.ip to director.hostname

### PR DESCRIPTION
**Pull request by viktoryiakotava**

### CODE REVIEW

**Comment by jncd** [comment]
Hi @ViktoriyaKotova 
That's a long sentence that you added. Without already knowing the product, I can't parse it. 
Can I substitute any of the following:

Out-the-box, users get:
+ Retrieving and parsing of logs received from PCF
+ Secure authorized access to these logs in Kibana
+ Useful dashboards and search queries to start log analysis

or 

Out-the-box, users get:
+ Retrieving and parsing of logs received from PCF
+ Secure authorized access to these logs in Kibana and useful dashboards
+ Search queries to start log analysis

Out-the-box, users get:
+ Retrieving and parsing of logs received from PCF
+ Secure authorized access to these logs in Kibana
+ Useful dashboards
+ Search queries to start log analysis

Thanks for doing the fast fix for IP address vs hostname.

**Comment by viktoryiakotava** [comment]
Hi Jane, 
First option works fine, thank you!

**Comment by jncd** [comment]
@ViktoriyaKotova Done! Thanks. And thanks for the fast fix for IP address vs hostname. I worked with Mikey Boldt to standardize what we say in the release notes about it too.

**Comment by viktoryiakotava** [comment]
Thanks for your great work!

**Pull request merged**
